### ISSUE TITLE
Analyticsd constant crashing

### ISSUE THREAD

**Issue by Motive101** [rllbe/entitlementfix#1]
I’ve tried rebooting, ldrestart, guicache, icleaner  and safemode. Nothing solved the issue other than uninstalling your package.

**Comment by rllbe** [comment]
Could you please update my repo and install the new version, and see if it fixes the problem for you?

**Comment by blanxd** [comment]
for me (on u0) analyticsd did crash but, only right after installing the tweak, later everything worked fine. With ver.0.0.2 it didn't crash at all. I was literally just investigating this, reading my crash logs, when you posted the update so I saw your message appear live here. I'll be back if I can discover somethign from my crash log, but someone should post one if they have it crashing constantly because this must be some different setup.

**Comment by blanxd** [comment]
> for me (on u0) analyticsd did crash but, only right after installing the tweak, later everything worked fine. With ver.0.0.2 it didn't crash at all. I was literally just investigating this, reading my crash logs, when you posted the update so I saw your message appear live here. I'll be back if I can discover somethign from my crash log, but someone should post one if they have it crashing constantly because this must be some different setup.

or @rllbe would you like to see the crashlog anyway? which one do you prefer, .ips or the [cr4shed] text?
EDIT: uuh you probably don't, my crashlog is about exactly that vm_region thing you addressed in 0.0.2.

**Comment by Motive101** [comment]
On Reddit, seems that it breaks Game Center, I don’t play games on my phone so no worries there. Updating worked. Thank you.
